### ISSUE TITLE
Yahoo Exchange failing on appveyor

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/yappy#136]
````
1) Yahoo XChange forex rates should only return currencies of interest:
     SuperagentPromiseError: cannot GET http://query.yahooapis.com/v1/public/yql (400)
      at C:\projects\yappy\lib\superagent-bluebird-promise.js:72:19
      at Request.callback (C:\projects\yappy\node_modules\superagent\lib\node\index.js:800:3)
      at IncomingMessage.<anonymous> (C:\projects\yappy\node_modules\superagent\lib\node\index.js:997:12)
      at emitNone (events.js:73:20)
      at IncomingMessage.emit (events.js:167:7)
      at endReadableNT (_stream_readable.js:906:12)
      at nextTickCallbackWith2Args (node.js:455:9)
      at process._tickCallback (node.js:369:17)
````

**Comment by richardschneider** [comment]
Added some logging and now its working!  I bet its a timeout issue. 

Will leave this open for a while.
