### ISSUE TITLE
sending invalid JSON data

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/yappy#88]
````
[
    { "op": "replace", "path": "/name/0/text", value: "yogi (1)" },
    { "op": "replace", "path": "/name/20/text", "value": "yogi (1)" }
]
````

blows up with
````
TypeError: res.sendError is not a function
   at /home/ubuntu/workspace/lib/server/index.js:26:7
   at Layer.handle_error (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:71:5)
````

**Comment by richardschneider** [comment]
Cannot reproduce.  An error message is now returned.

````javascript
{ message: 'Cannot perform the operation at a path that does not exist',
  details: 
   { name: 'OPERATION_PATH_UNRESOLVABLE',
     index: 1,
     operation: { op: 'replace', path: '/name/20/text', value: 'yogi (1)' } },
  _metadata: { self: '/api/bear/undefined', type: 'bear' } }
````
